### PR TITLE
New Feature 

### PR DESCRIPTION
**Pull request by Tejas12972**
Added DaBaby function
```js
await daBaby(url)
```
Preview
https://cdn.discordapp.com/attachments/840619319921737750/862362672452206672/Screen_Shot_2021-07-07_at_12.01.19_PM.png

### CODE REVIEW

**Comment by KarimX32** [comment]
Make it bigger and move it down a bit

**Comment by Tejas12972** [comment]
canvas size is 900,900. Ill adjust it to make it larger and move the icon down

**Comment by KarimX32** [comment]
show preview once its done

**Comment by RaZeSloth** [comment]
Make it as a✨**class**✨

**Comment by KarimX32** [comment]
no need :kekw:

**Comment by KarimX32** [comment]
any news yet ;-;

**Comment by Tejas12972** [comment]
Ye lemme just commit new code I was sleeping, and @RaZegame no need for a class 😂 , its easier to use without one

**Comment by Tejas12972** [comment]
Alright, I move it down/
https://cdn.discordapp.com/attachments/840619319921737750/862671695071936549/DaBaby.png

I couldn't rly figure out how to make it bigger, tried adjusting canvas size but no luck 🤷

**Comment by KarimX32** [comment]
pr the dev branch we can try to move it down it ain't that hard

**Comment by Tejas12972** [comment]
I moved it down with a lil resize of the canvas, just needa make the image itself bigger as you said previously

**Comment by Tejas12972** [comment]
Ill Pr dev branch

**Comment by Tejas12972** [comment]
nvm its already merged with main

**Comment by RaZeSloth** [comment]
I tried to make it better
```js
const Discord = require("discord.js");
const Canvas = require('canvas')
/**
 * Create a daBaby image from a URL for a Discord.js Bot
 * @param {String} person_url The "dababy"
 *@returns {Discord.MessageAttachment}
 */

module.exports = async function daBaby(url) {
    if (!url) throw new TypeError("Dababy: No url provided");

    const canvas = Canvas.createCanvas(320, 320);
    const ctx = canvas.getContext('2d');
    const background = await Canvas.loadImage('https://media.pitchfork.com/photos/5c7d4c1b4101df3df85c41e5/1:1/w_320/Dababy_BabyOnBaby.jpg');
    ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

    const imageURL = await Canvas.loadImage(url);
    ctx.beginPath();
    ctx.arc(150, 150, 50, 0, Math.PI * 2, false);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(imageURL, 50 * 2, 50 * 2, 200/2, 200/2);
    
    return new Discord.MessageAttachment(canvas.toBuffer(), 'DaBaby.png')


}
```
And the output:
image

**Comment by Tejas12972** [comment]
ok bro i see you 😳

**Comment by RaZeSloth** [comment]
Proton, better like dA prOtOn

**Comment by ghost** [comment]
:eyes:

**Comment by RaZeSloth** [comment]
So, what is happening with this pr?

**Comment by Tejas12972** [comment]
Idk, @KarimX32 if you wanna make it bigger you gotta make the back ground image bigger, I just found one off of google so ig just resize it

**Pull request merged**
