### PR TITLE
Changed button pagination 

### PR DESCRIPTION
**Pull request by Tejas12972**
Change button pagination for more user friendly and use discord-buttons

preview.

https://cdn.discordapp.com/attachments/840619319921737750/870009196173738074/2021-07-28_14-25-11.mp4

usage

```js

 let embed1 = new Discord.MessageEmbed() // the first embed
		.setTitle("1")

		let embed2 = new Discord.MessageEmbed() // the second embed
		.setTitle("2")
		
		let pages = [embed1, embed2] // putting the embeds into an array to paginate

		await ultrax.ButtonPaginator({
			message: message, // the discord message
			embeds: pages, // Array of embeds
			button1: {
				label: '<<', // the label of the back button
				style: 'gray', // discord button style
			},
			button2: {
				label: '>>',  // the label of the forward button
				style: 'gray', // discord button style
			},
			timeActive: 10, // the time that the buttons are valid, in MS
			setDisabled: true, // should the buttons be setDisbaled after the allocated time 
			invalidUser: {
				ephemeralReply: true, // should the reply be ephemeral if the button clicker is not the message author
				message: 'only the message author can use the buttons!', // the message to be send when such event occurs
			}
		});```

### CODE REVIEW

**Comment by Tejas12972** [comment]
a lot of ppl getting err whilst running old pagination so changed it

**Comment by RaZeSloth** [comment]
But why use, the "discord-buttons" package? It is going to be outdated in v13. And there should be our buttons system, with raw api requests.

**Comment by reinacchi** [comment]
This PR would fail anyway. You should refrain from using discord-buttons.

If you could use a raw event instead, I would accept it.

**Comment by BIntelligent** [comment]
I'll merge it but you don't check if user has package or no, so you're forcing someone to download discord buttons to use ultrax package

**Comment by ghost** [comment]
I think using external packages to simplify such a small thing is not needed and can be done with raw API.

**Comment by KarimX32** [comment]
we don't need another package, it's just useless.

**Pull request closed without merging**
