### PR TITLE
Added the boostImage() function and the Boost event.

### PR DESCRIPTION
**Pull request by Iliannnn**
Its in V13 UwU

### CODE REVIEW

**Comment by RaZeSloth** [comment]
Typings?

**Comment by Iliannnn** [comment]
I did .. ?

**Comment by Iliannnn** [comment]
Oh wait, I think I didn't commited the index.d.ts/index.js fuck

**Comment by Iliannnn** [comment]
Nope, I did..

**Comment by RaZeSloth** [comment]
oh wow

**Comment by KarimX32** [comment]
wot

**Pull request closed without merging**
