### PR TITLE
Wikipedia Command

### PR DESCRIPTION
**Pull request by Tejas12972**
PR for wikipedia command, added the class, changed ReadME

```js
const sleep = require('./functions/sleep'),
    passGen = require('./functions/passGen'),
    bin = require('./functions/bin'),
    inviteLogger = require("./functions/invite-logger"),
    _checkUpdate = require("./functions/checkUpdates"),
    ButtonPaginator = require("./functions/button-embed-reactor"),
    welcomeImage = require('./functions/welcomeImage'),
    Wikipedia = require('../classes/Wikipedia')



_checkUpdate()
module.exports = {
    sleep,
    passGen,
    bin,
    inviteLogger,
    ButtonPaginator,
    welcomeImage
};```

just need to change index.js like this before publish

>

### CODE REVIEW

**Comment by BIntelligent** [comment]
i love it 
Screenshot_20210701-191731
IF QUERY, RETURN ERROR.

give me your discord as well. so i can thank you.

**Comment by Tejas12972** [comment]
shi lmao, its supposed do be if(!query),

disc, is ``_Tejas#2007``

**Comment by BIntelligent** [comment]
Screenshot_20210701-191957
await await great!

Screenshot_20210701-192108
 make first letter bigger

**Comment by BIntelligent** [comment]
i suggest proof read it your self than ill review my self. I'll look into it after 30 mins so proof read.

**Comment by Tejas12972** [comment]
alright

**Comment by BIntelligent** [comment]
Screenshot_20210701-192346
wikipedia is defined but never used. Great!

**Comment by BIntelligent** [comment]
Screenshot_20210701-192656
Screenshot_20210701-192634
this.channel is not defined and where do u send embed??

**Comment by Tejas12972** [comment]
Oh thought I fixed that changes must've not been pushed to GitHub, I'mma look over and push again

**Comment by BIntelligent** [comment]
i suggest testing it locally by putting token in example bot and using it your self and try break it when you think its unbreakable let me know

**Comment by Tejas12972** [comment]
Ok

**Comment by Tejas12972** [comment]
Alright so I found an issue when there's too many requests in the URL, solved this with a when fetching the response, other than that I think its good

**Comment by BIntelligent** [comment]
so now i look for bugs? did you run the bot to test it? send ss of command working

**Comment by Tejas12972** [comment]
I ran test of it, here is the SS

https://cdn.discordapp.com/attachments/840619319921737750/860174973263806484/Screen_Shot_2021-07-01_at_11.08.12_AM.png

it might be wired as the screen shots on Mac are kinda blue colored

**Comment by BIntelligent** [comment]
i reviewed code, looks fine. Thanks for contributing

**Pull request merged**
