### PR TITLE
Fixed some bugs in README.md ;-;

### PR DESCRIPTION
**Pull request by Iliannnn**
- Because in some links there was a header id with capital letters after the #, this don't work and you were therefore not redirected to the method or event.

- Fixed a bug where it was not shown how 'boosterCard' was defined in the boostImage() method.

- Added `www.` to links that didn't already have it ._.

- On line 3 the bin methodhad the link of the welcomeImage() method, this has now also been solved.

@BIntelligent These are very stupid mistakes so merge this quickly UwU, and if you want the package version to be changed, do it yourself ._.
<br>
fuck-go-fuck-yourself

### CODE REVIEW

**Comment by reinacchi** [comment]
I would approve for rest except the `www` on domains. Discord never have these exist and it'll redirect you to the original domain. `www.discord.com` -> `discord.com` which is already correct at first. You're just making things unclear. The opposite of the Discord domain, NPM uses `www` if you take a look closely when directing to the NPM site.

**Comment by Iliannnn** [comment]
I don't use discord.com anywhere here, just checked and all links work except the `discord.js.org` with the www in front, so I'll remove that and then everything is fine :)

**Comment by reinacchi** [comment]
If you fix them just to satisfy your basis, I prefer your own personal fork instead of PR since you're not inputting the original resources (modified) and I assume this PR needs few changes before merging but eh it's merged either way...

**Comment by Iliannnn** [comment]
> If you fix them just to satisfy your basis, I prefer your own personal fork instead of PR since you're not inputting the original resources (modified) and I assume this PR needs few changes before merging but eh it's merged either way...

I just tweaked the readme a bit, it's not like much can go wrong, cry about it 😂

**Comment by reinacchi** [comment]
Ok, this seems a bit off-topic but decisions are on the owner of this repo. If this repo was mine, I would've declined most PRs for being low effort.

**Comment by ghost** [comment]
Top development quality.

**Comment by BIntelligent** [comment]
> Top development quality.

SEE I SAID U @Iliannnn  he is in the server using a alt

**Comment by Iliannnn** [comment]
> Top development quality.

Sureeeeee

**Comment by Iliannnn** [comment]
> > Top development quality.
> 
> SEE I SAID U @Iliannnn  he is in the server using a alt

Iknow 😂

**Comment by RaZeSloth** [comment]
Karim is dead as always

**Comment by KarimX32** [comment]
> Karim is dead as always

Are you sure about that?

**Comment by RaZeSloth** [comment]
> > Karim is dead as always
> 
> Are you sure about that?

@BIntelligent has more commits than you ._.

**Comment by BIntelligent** [comment]
ye im intelligent

**Comment by RaZeSloth** [comment]
ohok

**Pull request merged**
